# Site settings
title: Random Bits
email: you@guess.it
description: > # this means to ignore newlines until "baseurl:"
  Rants, thoughts and findings related (or not) to software / technologies.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://houtianze.github.io" # the base hostname & protocol for your site
twitter_username: ibic
github_username: houtianze

# Build settings
markdown: kramdown
